name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x]

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install

        - name: Chrome driver
          uses: nanasess/setup-chromedriver@v1
          with:
            # Optional: do not specify to match Chrome's version
            chromedriver-version: '88.0.4324.96'
        - run: |
            pip install selenium
            pip install webdriver_manager
            export DISPLAY=:99
            chromedriver --url-base=/wd/hub &
            sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
        - run: |
            python3 selenium/test.py

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
      env:
        CI: false
        
    - name: Install Firebase
      run: npm install --save firebase
        
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run: surge ./build https://sqr-project-front.surge.sh --token ${{secrets.SURGE_TOKEN}}
