name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --if-present
      env:
        CI: false
        
    - name: Install Firebase
      run: npm install --save firebase
        
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run: surge ./build https://sqr-project-front.surge.sh --token ${{secrets.SURGE_TOKEN}}
